#!/usr/bin/env node
/**
 * ADR Manager — Architecture Decision Records
 *
 * Format: MADR (Markdown Any Decision Records)
 * https://adr.github.io/madr/
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// ─── Types ───────────────────────────────────────────────────────────────

export interface ADR {
  id: number;
  title: string;
  status: "proposed" | "accepted" | "deprecated" | "superseded";
  date: string;
  filename: string;
  content: string;
}

export interface ADRCreateOptions {
  title: string;
  status?: ADR["status"];
  supersedes?: number;
}

// ─── Constants ──────────────────────────────────────────────────────────

const ADR_DIR = "docs/adr";
const ADR_TEMPLATE = `# {id}. {title}

- **Status:** {status}
- **Date:** {date}
- **Supersedes:** {supersedes}

## Context

What is the issue that we're seeing that is motivating this decision or change?

## Decision

What is the change that we're actually proposing or doing?

## Consequences

What becomes easier or more difficult to do because of this change?

---

*ADR generated by coder-workflow*
`;

// ─── ADR Operations ────────────────────────────────────────────────────

function getADRDir(): string {
  return join(process.cwd(), ADR_DIR);
}

function ensureADRDir(): string {
  const dir = getADRDir();
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  return dir;
}

export function initADR(): { dir: string } {
  const dir = ensureADRDir();
  // Create a README if not exists
  const readmePath = join(dir, "README.md");
  if (!existsSync(readmePath)) {
    writeFileSync(
      readmePath,
      [
        "# Architecture Decision Records",
        "",
        "This directory contains Architecture Decision Records (ADRs).",
        "",
        "Each ADR documents an architectural decision, its context, and its consequences.",
        "",
        "## How to use",
        "",
        "```bash",
        'coder-workflow adr new "<decision title>"',
        "coder-workflow adr list",
        "coder-workflow adr status <id> --status accepted",
        "coder-workflow adr graph",
        "```",
        "",
        "## Status Definitions",
        "",
        "| Status | Meaning |",
        "|---|---|",
        "| Proposed | Under discussion |",
        "| Accepted | Agreed upon and implemented |",
        "| Deprecated | No longer recommended |",
        "| Superseded | Replaced by a newer ADR |",
      ].join("\n"),
      "utf-8",
    );
  }
  return { dir };
}

export function createADR(options: ADRCreateOptions): ADR {
  const dir = ensureADRDir();

  // Get next ID
  const existing = listADRs();
  const nextId = existing.length > 0 ? Math.max(...existing.map((a) => a.id)) + 1 : 1;

  // Create slug from title
  const slug = options.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);

  const date = new Date().toISOString().split("T")[0];
  const filename = `${String(nextId).padStart(4, "0")}-${slug}.md`;
  const filePath = join(dir, filename);

  const content = ADR_TEMPLATE.replace(/{id}/g, String(nextId))
    .replace(/{title}/g, options.title)
    .replace(/{status}/g, options.status ?? "proposed")
    .replace(/{date}/g, date)
    .replace(/{supersedes}/g, options.supersedes ? `ADR-${options.supersedes}` : "None");

  writeFileSync(filePath, content, "utf-8");

  return {
    id: nextId,
    title: options.title,
    status: options.status ?? "proposed",
    date,
    filename,
    content,
  };
}

export function listADRs(): ADR[] {
  const dir = getADRDir();
  if (!existsSync(dir)) return [];

  const adrs: ADR[] = [];
  const files = readdirSync(dir).filter((f) => f.match(/^\d{4}-.+\.md$/) && f !== "README.md");

  for (const file of files) {
    try {
      const content = readFileSync(join(dir, file), "utf-8");
      const id = parseInt(file, 10);
      const title = extractTitle(content, file);
      const status = extractStatus(content);
      const date = extractDate(content);

      adrs.push({
        id: Number.isNaN(id) ? adrs.length + 1 : id,
        title,
        status,
        date,
        filename: file,
        content,
      });
    } catch {
      // skip corrupted files
    }
  }

  adrs.sort((a, b) => a.id - b.id);
  return adrs;
}

export function getADR(id: number): ADR | undefined {
  return listADRs().find((a) => a.id === id);
}

export function updateADRStatus(id: number, status: ADR["status"]): ADR | undefined {
  const adr = getADR(id);
  if (!adr) return undefined;

  const dir = getADRDir();
  const filePath = join(dir, adr.filename);

  const updated = adr.content.replace(/\*\*Status:\*\* .+/, `**Status:** ${status}`);

  writeFileSync(filePath, updated, "utf-8");

  return { ...adr, status, content: updated };
}

// ─── Graph ──────────────────────────────────────────────────────────────

export function generateADRGraph(): string {
  const adrs = listADRs();
  if (adrs.length === 0) return "No ADRs found.";

  const lines = ["```mermaid", "graph LR"];

  for (const adr of adrs) {
    const statusIcon =
      adr.status === "accepted"
        ? "✅"
        : adr.status === "proposed"
          ? "💡"
          : adr.status === "deprecated"
            ? "❌"
            : "➡️";
    const label = `${statusIcon} ${adr.id}: ${adr.title.slice(0, 40)}`;
    lines.push(`  ADR${adr.id}["${label}"]`);
    lines.push(`  style ADR${adr.id} fill:${statusColor(adr.status)}`);
  }

  // Link supersedes relationships
  for (const adr of adrs) {
    const supersedes = extractSupersedes(adr.content);
    if (supersedes) {
      lines.push(`  ADR${adr.id} -.->|supersedes| ADR${supersedes}`);
    }
  }

  lines.push("```");
  return lines.join("\n");
}

function statusColor(status: ADR["status"]): string {
  switch (status) {
    case "accepted":
      return "#d4edda";
    case "proposed":
      return "#fff3cd";
    case "deprecated":
      return "#f8d7da";
    case "superseded":
      return "#e2e3e5";
  }
}

// ─── Parsing Helpers ───────────────────────────────────────────────────

function extractTitle(content: string, filename: string): string {
  const match = content.match(/^#\s+\d+\.\s+(.+)/m);
  if (match) return match[1].trim();

  // Fall back to filename
  return filename.replace(/^\d+-/, "").replace(/\.md$/, "").replace(/-/g, " ");
}

function extractStatus(content: string): ADR["status"] {
  const match = content.match(/\*\*Status:\*\*\s+(.+)/i);
  if (!match) return "proposed";

  const status = match[1].trim().toLowerCase();
  if (status.startsWith("accept")) return "accepted";
  if (status.startsWith("propos")) return "proposed";
  if (status.startsWith("deprec")) return "deprecated";
  if (status.startsWith("supers")) return "superseded";
  return "proposed";
}

function extractDate(content: string): string {
  const match = content.match(/\*\*Date:\*\*\s+(.+)/i);
  return match ? match[1].trim() : new Date().toISOString().split("T")[0];
}

function extractSupersedes(content: string): number | undefined {
  const match = content.match(/supersedes.*?ADR[-\s]*(\d+)/i);
  return match ? parseInt(match[1], 10) : undefined;
}

// ─── CLI Formatting ────────────────────────────────────────────────────

export function formatADRList(adrs: ADR[]): string {
  if (adrs.length === 0)
    return "No ADRs found. Use 'coder-workflow adr new <title>' to create one.";

  const lines = [
    "┌──────┬────────────────────────────────────────────────┬────────────┬────────────┐",
  ];
  lines.push("│  ID  │ Title                                          │ Status     │ Date       │");
  lines.push("├──────┼────────────────────────────────────────────────┼────────────┼────────────┤");

  for (const adr of adrs) {
    const id = String(adr.id).padEnd(4);
    const title = adr.title.slice(0, 46).padEnd(46);
    const status = adr.status.padEnd(10);
    const date = adr.date.padEnd(10);
    lines.push(`│ ${id} │ ${title} │ ${status} │ ${date} │`);
  }

  lines.push("└──────┴────────────────────────────────────────────────┴────────────┴────────────┘");
  return lines.join("\n");
}
