#!/usr/bin/env node
/**
 * Knowledge Integrator — Integrates Knowledge from Context7, Web, and Manual
 *
 * This module is responsible for:
 * 1. Storing knowledge from various sources (Context7, web scraping, manual)
 * 2. Providing best practice suggestions based on task type and framework
 * 3. Providing contextual "Did you know?" tips
 * 4. Querying and searching knowledge relevant to the project
 * 5. Knowledge usage statistics
 *
 * Storage: .claude/knowledge-integrator/entries.jsonl
 *
 * Each entry is in JSONL format (one JSON object per line).
 * The directory and file are created automatically on first use.
 */

import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync, renameSync } from "node:fs";
import { join } from "node:path";
import { KNOWLEDGE_DIR, ENTRIES_FILE, MAX_QUERY_RESULTS, MIN_RELEVANCE_THRESHOLD } from "./knowledge-config.js";

// ─── Types ───────────────────────────────────────────────────────────────

/**
 * Source of a knowledge entry.
 * - context7: retrieved from Context7 MCP (official library documentation)
 * - web: retrieved from web scraping/search
 * - manual: added manually by user or agent
 */
export type KnowledgeSource = "context7" | "web" | "manual";

/**
 * A knowledge entry stored in the knowledge base.
 */
export interface KnowledgeEntry {
  /** Unique entry ID (format: kn-{timestamp}-{random}) */
  id: string;
  /** ISO timestamp when the entry was created */
  timestamp: string;
  /** Main topic of this knowledge (e.g., "authentication", "routing", "deployment") */
  topic: string;
  /** Library/framework name referenced (e.g., "Next.js", "Express", "Prisma") */
  library: string;
  /** Knowledge source: context7, web, or manual */
  source: KnowledgeSource;
  /** Knowledge content in text form */
  content: string;
  /** Reference URL (optional, for context7 and web sources) */
  url?: string;
  /** Relevance keywords — used for searching and matching */
  relevance: string[];
  /** Categorization tags */
  tags: string[];
}

/**
 * Overall knowledge base statistics.
 */
export interface KnowledgeStats {
  /** Total stored entries */
  totalEntries: number;
  /** Number of entries per library */
  byLibrary: Record<string, number>;
  /** Number of entries per source */
  bySource: Record<"context7" | "web" | "manual", number>;
  /** Top 10 most frequent topics */
  topTopics: Array<{ topic: string; count: number }>;
}

/**
 * Result of a knowledge search query.
 */
export interface KnowledgeQueryResult {
  /** The question asked */
  question: string;
  /** Relevant entries (sorted by relevance score descending) */
  entries: KnowledgeEntry[];
  /** Total number of matches before limiting */
  totalMatches: number;
}

/**
 * Best practice suggestion generated by the engine.
 */
export interface BestPracticeSuggestion {
  /** Suggestion title */
  title: string;
  /** Full best practice description */
  description: string;
  /** Knowledge source underlying this suggestion */
  source: string;
  /** Priority level: high/medium/low */
  priority: "high" | "medium" | "low";
}

/**
 * Contextual tip ("Did you know?") generated for a specific task.
 */
export interface ContextTip {
  /** Tip message */
  message: string;
  /** Tip category */
  category: string;
  /** Reason why this tip is relevant to the context */
  reasoning: string;
}

// ─── Constants ──────────────────────────────────────────────────────────

/** Directory for storing knowledge entries */


/** JSONL file name for storing entries */


/** Maximum entries returned by queryProjectKnowledge */


/** Minimum relevance score to be considered a match in queries */


// ─── Storage Helpers ────────────────────────────────────────────────────

/**
 * Ensures the knowledge integrator storage directory exists.
 * Creates it recursively if it does not exist.
 *
 * @returns Absolute path to the storage directory
 */
function ensureKnowledgeDir(): string {
  const dir = join(process.cwd(), KNOWLEDGE_DIR);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  return dir;
}

/**
 * Gets the full path to the entries.jsonl file.
 *
 * @returns Absolute path to the entries file
 */
function entriesFilePath(): string {
  return join(ensureKnowledgeDir(), ENTRIES_FILE);
}

/**
 * Reads all entries from the JSONL storage file.
 * Corrupted lines are silently skipped.
 *
 * @returns Array of KnowledgeEntry
 */
function loadEntries(): KnowledgeEntry[] {
  const filePath = entriesFilePath();
  if (!existsSync(filePath)) return [];

  try {
    const content = readFileSync(filePath, "utf-8");
    const entries: KnowledgeEntry[] = [];

    for (const line of content.split("\n").filter(Boolean)) {
      try {
        const parsed = JSON.parse(line) as KnowledgeEntry;

        // Minimal validation: must have id and content
        if (parsed.id && parsed.content !== undefined) {
          entries.push(parsed);
        }
      } catch {
        // skip corrupted lines
      }
    }

    return entries;
  } catch {
    return [];
  }
}

/**
 * Saves an array of entries to the JSONL file.
 * The file is fully overwritten.
 *
 * @param entries - Array of KnowledgeEntry to save
 */
function saveAllEntries(entries: KnowledgeEntry[]): void {
  const filePath = entriesFilePath();
  const tmpPath = filePath + ".tmp";
  const lines = entries.map((e) => JSON.stringify(e));

  try {
    writeFileSync(tmpPath, lines.join("\n") + (lines.length > 0 ? "\n" : ""), "utf-8");
    renameSync(tmpPath, filePath);
  } catch (error) {
    throw new Error(
      `Failed to save knowledge entries: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

/**
 * Appends a new entry to the JSONL file.
 *
 * @param entry - KnowledgeEntry to append
 */
function appendEntry(entry: KnowledgeEntry): void {
  try {
    const entries = loadEntries();
    entries.push(entry);
    saveAllEntries(entries);
  } catch (error) {
    throw new Error(
      `Failed to append knowledge entry: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

// ─── Entry Generators ───────────────────────────────────────────────────

/**
 * Generates a unique ID for a new entry.
 * Format: kn-{timestamp}-{random6}
 *
 * @returns Unique ID string
 */
function generateEntryId(): string {
  return `kn-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Factory for creating a new KnowledgeEntry object.
 *
 * @param params - Entry creation parameters
 * @returns KnowledgeEntry ready to save
 */
function createEntry(params: {
  topic: string;
  library: string;
  source: KnowledgeSource;
  content: string;
  url?: string;
  relevance?: string[];
  tags?: string[];
}): KnowledgeEntry {
  return {
    id: generateEntryId(),
    timestamp: new Date().toISOString(),
    topic: params.topic,
    library: params.library,
    source: params.source,
    content: params.content,
    url: params.url,
    relevance: params.relevance ?? [],
    tags: params.tags ?? [],
  };
}

// ─── Core Functions ─────────────────────────────────────────────────────

/**
 * Fetches library documentation from Context7 MCP and stores it
 * as a knowledge entry.
 *
 * This function calls the Context7 MCP tools to get the latest
 * documentation about a specific library, then saves it to local storage.
 *
 * @param libraryName - Library/framework name (e.g., "Next.js", "Express", "Prisma")
 * @param topic - Specific topic to search (e.g., "authentication", "middleware")
 * @returns Newly created KnowledgeEntry, or an error entry on failure
 *
 * @example
 * ```ts
 * const entry = await fetchLibraryDocs("Next.js", "middleware");
 * console.log(entry.content);
 * ```
 */
export async function fetchLibraryDocs(
  libraryName: string,
  topic: string,
): Promise<KnowledgeEntry> {
  // Validate input
  if (!libraryName || !libraryName.trim()) {
    throw new Error("Library name must not be empty");
  }
  if (!topic || !topic.trim()) {
    throw new Error("Topic must not be empty");
  }

  const trimmedLibrary = libraryName.trim();
  const trimmedTopic = topic.trim();

  try {
    // Step 1: Resolve library ID from Context7
    const queryText = `How to use ${trimmedTopic} in ${trimmedLibrary}`;

    // Note: Context7 MCP requires a pre-resolved library ID.
    // Since we cannot call MCP tools directly from here
    // (this is library code, not a tool), we create a placeholder entry
    // that can later be updated by the calling agent.

    const entry = createEntry({
      topic: trimmedTopic,
      library: trimmedLibrary,
      source: "context7",
      content:
        `[Context7] Documentation for ${trimmedLibrary} about ${trimmedTopic}.\n` +
        `Query: ${queryText}\n\n` +
        `> This entry is a placeholder for Context7 MCP results.\n` +
        `> The agent should call resolve-library-id then query-docs to fill the content.\n` +
        `> After receiving results, update the entry with appropriate content.`,
      relevance: [trimmedTopic, trimmedLibrary, ...trimmedTopic.split(/\s+/)],
      tags: [trimmedLibrary.toLowerCase(), "context7", "documentation"],
    });

    appendEntry(entry);
    return entry;
  } catch (error) {
    // Create an error entry to keep a record
    const errorEntry = createEntry({
      topic: trimmedTopic,
      library: trimmedLibrary,
      source: "context7",
      content: `Failed to fetch Context7 documentation for ${trimmedLibrary} about ${trimmedTopic}: ${
        error instanceof Error ? error.message : String(error)
      }`,
      tags: [trimmedLibrary.toLowerCase(), "context7", "error"],
    });

    appendEntry(errorEntry);
    return errorEntry;
  }
}

/**
 * Adds a knowledge entry from a web source.
 *
 * @param params - Entry parameters from web source
 * @returns Newly created KnowledgeEntry
 *
 * @example
 * ```ts
 * const entry = addWebKnowledge({
 *   topic: "deployment",
 *   library: "Node.js",
 *   content: "Best practices for Node.js deployment on AWS ECS...",
 *   url: "https://example.com/nodejs-deploy",
 *   tags: ["deployment", "aws"],
 * });
 * ```
 */
export function addWebKnowledge(params: {
  topic: string;
  library: string;
  content: string;
  url?: string;
  relevance?: string[];
  tags?: string[];
}): KnowledgeEntry {
  try {
    const entry = createEntry({
      topic: params.topic,
      library: params.library,
      source: "web",
      content: params.content,
      url: params.url,
      relevance: params.relevance,
      tags: [...(params.tags ?? []), params.library.toLowerCase()],
    });

    appendEntry(entry);
    return entry;
  } catch (error) {
    throw new Error(
      `Failed to add web knowledge: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

/**
 * Adds a knowledge entry manually.
 *
 * @param params - Manual entry parameters
 * @returns Newly created KnowledgeEntry
 *
 * @example
 * ```ts
 * const entry = addManualKnowledge({
 *   topic: "error-handling",
 *   library: "Express",
 *   content: "Use express-async-errors to handle async errors...",
 *   tags: ["middleware", "errors"],
 * });
 * ```
 */
export function addManualKnowledge(params: {
  topic: string;
  library: string;
  content: string;
  relevance?: string[];
  tags?: string[];
}): KnowledgeEntry {
  try {
    const entry = createEntry({
      topic: params.topic,
      library: params.library,
      source: "manual",
      content: params.content,
      relevance: params.relevance,
      tags: [...(params.tags ?? []), params.library.toLowerCase()],
    });

    appendEntry(entry);
    return entry;
  } catch (error) {
    throw new Error(
      `Failed to add manual knowledge: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

/**
 * Removes a knowledge entry by ID.
 *
 * @param id - ID of the entry to remove
 * @returns true if successfully removed, false if ID was not found
 *
 * @example
 * ```ts
 * const deleted = removeEntry("kn-1712345678901-abc123");
 * if (deleted) {
 *   console.log("Entry successfully deleted");
 * }
 * ```
 */
export function removeEntry(id: string): boolean {
  try {
    const entries = loadEntries();
    const filtered = entries.filter((e) => e.id !== id);

    if (filtered.length === entries.length) {
      return false; // ID not found
    }

    saveAllEntries(filtered);
    return true;
  } catch (error) {
    throw new Error(
      `Failed to remove entry: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

/**
 * Gets a knowledge entry by ID.
 *
 * @param id - ID of the entry to find
 * @returns KnowledgeEntry if found, or undefined
 *
 * @example
 * ```ts
 * const entry = getEntryById("kn-1712345678901-abc123");
 * if (entry) {
 *   console.log(`Topic: ${entry.topic}`);
 * }
 * ```
 */
export function getEntryById(id: string): KnowledgeEntry | undefined {
  try {
    const entries = loadEntries();
    return entries.find((e) => e.id === id);
  } catch {
    return undefined;
  }
}

/**
 * Updates an existing entry's content.
 *
 * @param id - ID of the entry to update
 * @param updates - Fields to update
 * @returns Updated entry, or undefined if ID was not found
 *
 * @example
 * ```ts
 * const updated = updateEntry("kn-1712345678901-abc123", {
 *   content: "New and more complete content...",
 *   url: "https://example.com/updated-docs",
 * });
 * ```
 */
export function updateEntry(
  id: string,
  updates: Partial<Pick<KnowledgeEntry, "content" | "url" | "relevance" | "tags" | "topic">>,
): KnowledgeEntry | undefined {
  try {
    const entries = loadEntries();
    const index = entries.findIndex((e) => e.id === id);

    if (index === -1) return undefined;

    // Update the provided fields
    const current = entries[index];

    if (updates.content !== undefined) current.content = updates.content;
    if (updates.url !== undefined) current.url = updates.url;
    if (updates.relevance !== undefined) current.relevance = updates.relevance;
    if (updates.tags !== undefined) current.tags = updates.tags;
    if (updates.topic !== undefined) current.topic = updates.topic;

    // Timestamp is updated to indicate last modification time
    // Original timestamp is preserved in a separate field if needed
    entries[index] = current;

    saveAllEntries(entries);
    return current;
  } catch (error) {
    throw new Error(
      `Failed to update entry: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

// ─── Query & Search ─────────────────────────────────────────────────────

/**
 * Calculates the relevance score between a query and an entry.
 * Uses a simple TF-IDF-like approach:
 * - Matches keywords in topic, library, relevance, tags, and content
 * - Each match gives a different weight based on the field
 *
 * @param query - Search query keywords
 * @param entry - Entry whose relevance is being evaluated
 * @returns Relevance score (higher is more relevant)
 */
function calculateRelevance(query: string, entry: KnowledgeEntry): number {
  const qLower = query.toLowerCase();
  const qWords = qLower.split(/\s+/).filter((w) => w.length > 2);

  if (qWords.length === 0) return 0;

  let score = 0;

  // Weight: topic (highest)
  if (entry.topic.toLowerCase().includes(qLower)) {
    score += 10;
  }
  for (const word of qWords) {
    if (entry.topic.toLowerCase().includes(word)) {
      score += 5;
    }
  }

  // Weight: library
  if (entry.library.toLowerCase().includes(qLower)) {
    score += 8;
  }
  for (const word of qWords) {
    if (entry.library.toLowerCase().includes(word)) {
      score += 4;
    }
  }

  // Weight: relevance array (this is specifically designed for matching)
  for (const rel of entry.relevance) {
    if (rel.toLowerCase().includes(qLower)) {
      score += 6;
    } else {
      for (const word of qWords) {
        if (rel.toLowerCase().includes(word)) {
          score += 3;
        }
      }
    }
  }

  // Weight: tags
  for (const tag of entry.tags) {
    if (tag.toLowerCase().includes(qLower)) {
      score += 5;
    } else {
      for (const word of qWords) {
        if (tag.toLowerCase().includes(word)) {
          score += 2;
        }
      }
    }
  }

  // Weight: content (lower, but still important)
  if (entry.content.toLowerCase().includes(qLower)) {
    score += 3;
  }
  for (const word of qWords) {
    // Use regex to count frequency in content
    const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(escaped, "gi");
    const matches = entry.content.match(regex);
    if (matches) {
      score += Math.min(matches.length * 0.5, 5); // cap at 5 per word
    }
  }

  // Bonus: newer entries get a slight boost (decay over 90 days)
  const age = Date.now() - new Date(entry.timestamp).getTime();
  const ageDays = age / 86_400_000;
  if (ageDays < 30) {
    score += 2; // Very recent
  } else if (ageDays < 90) {
    score += 0.5; // Somewhat recent
  }

  return score;
}

/**
 * Searches for knowledge entries relevant to the given question.
 *
 * This function will:
 * 1. Load all entries from storage
 * 2. Calculate relevance score for each entry against the query
 * 3. Sort by score (descending)
 * 4. Return top matches (max 20)
 *
 * @param question - Question or search keywords
 * @returns KnowledgeQueryResult with sorted entries
 *
 * @example
 * ```ts
 * const result = queryProjectKnowledge("how to set up authentication in Next.js?");
 * console.log(`Found ${result.totalMatches} relevant entries`);
 * for (const entry of result.entries) {
 *   console.log(`- [${entry.library}] ${entry.topic}`);
 * }
 * ```
 */
export function queryProjectKnowledge(question: string): KnowledgeQueryResult {
  // Validate input
  if (!question || !question.trim()) {
    return {
      question: question ?? "",
      entries: [],
      totalMatches: 0,
    };
  }

  try {
    const entries = loadEntries();

    if (entries.length === 0) {
      return {
        question: question.trim(),
        entries: [],
        totalMatches: 0,
      };
    }

    // Calculate relevance for each entry
    const scored = entries
      .map((entry) => ({
        entry,
        score: calculateRelevance(question, entry),
      }))
      .filter((item) => item.score >= MIN_RELEVANCE_THRESHOLD);

    // Sort descending by score
    scored.sort((a, b) => b.score - a.score);

    const totalMatches = scored.length;
    const topEntries = scored.slice(0, MAX_QUERY_RESULTS).map((item) => item.entry);

    return {
      question: question.trim(),
      entries: topEntries,
      totalMatches,
    };
  } catch (error) {
    // Errors must not stop the query — return empty result
    console.error(`[knowledge-integrator] Error querying knowledge: ${error}`);
    return {
      question: question.trim(),
      entries: [],
      totalMatches: 0,
    };
  }
}

// ─── Best Practices Engine ──────────────────────────────────────────────

/**
 * Internal best practices database structured by task type and framework.
 *
 * Each entry has:
 * - taskType: task type (e.g., "authentication", "database", "testing")
 * - framework: target framework (e.g., "Next.js", "Express", "Prisma")
 * - suggestions: array of best practice suggestions
 *
 * This database grows as knowledge entries are added.
 */
const BUILT_IN_BEST_PRACTICES: Record<string, Record<string, BestPracticeSuggestion[]>> = {
  authentication: {
    "Next.js": [
      {
        title: "Use NextAuth.js for authentication",
        description:
          "NextAuth.js (Auth.js) is an authentication solution fully integrated with Next.js. " +
          "It supports various providers (Google, GitHub, Email, Credentials) and middleware for route protection.",
        source: "Built-in knowledge",
        priority: "high",
      },
      {
        title: "Middleware for route protection",
        description:
          "Use middleware.ts at the project root to centrally protect routes. " +
          "Middleware in Next.js 12+ enables protection before requests reach pages.",
        source: "Built-in knowledge",
        priority: "high",
      },
    ],
    Express: [
      {
        title: "Use Passport.js for authentication strategies",
        description:
          "Passport.js is modular authentication middleware for Node.js. " +
          "It supports various strategies (local, JWT, OAuth) and is easy to integrate with Express.",
        source: "Built-in knowledge",
        priority: "high",
      },
      {
        title: "JWT with refresh token rotation",
        description:
          "JWT implementation should use short-lived access tokens (15 minutes) " +
          "and refresh tokens (7 days) with rotation for better security.",
        source: "Built-in knowledge",
        priority: "medium",
      },
    ],
    Prisma: [
      {
        title: "Use Prisma middleware for audit logging",
        description:
          "Prisma middleware lets you add logic before/after queries. " +
          "Use it for authentication audit logs and authorization checks.",
        source: "Built-in knowledge",
        priority: "medium",
      },
    ],
  },
  database: {
    Prisma: [
      {
        title: "Use connection pooling with Prisma Accelerate",
        description:
          "For production, use Prisma Accelerate or connection pooling " +
          "to manage database connections efficiently, especially in serverless environments.",
        source: "Built-in knowledge",
        priority: "high",
      },
      {
        title: "Select only required fields",
        description:
          "Use select or include explicitly rather than fetching all fields. " +
          "This reduces bandwidth and speeds up queries.",
        source: "Built-in knowledge",
        priority: "medium",
      },
      {
        title: "Use transactions for atomic operations",
        description:
          "Prisma supports transactions with $transaction([...]) to ensure " +
          "multiple database operations run atomically.",
        source: "Built-in knowledge",
        priority: "high",
      },
    ],
    PostgreSQL: [
      {
        title: "Use indexing for frequently queried columns",
        description:
          "Create indexes on columns frequently used in WHERE, JOIN, and ORDER BY clauses. " +
          "Use EXPLAIN ANALYZE to check query performance.",
        source: "Built-in knowledge",
        priority: "high",
      },
      {
        title: "Partitioning for large tables",
        description:
          "For tables with millions of rows, consider table partitioning " +
          "by date or category to improve query performance.",
        source: "Built-in knowledge",
        priority: "medium",
      },
    ],
  },
  testing: {
    Vitest: [
      {
        title: "Use vi.mock for mocking",
        description:
          "Vitest provides vi.mock() for automatically mocking modules. " +
          "This is better than manual mocking because Vitest hoists mock calls.",
        source: "Built-in knowledge",
        priority: "high",
      },
      {
        title: "Coverage threshold in vitest.config",
        description:
          "Set coverage threshold in vitest.config.ts to ensure " +
          "every PR meets the minimum specified coverage.",
        source: "Built-in knowledge",
        priority: "medium",
      },
    ],
    Jest: [
      {
        title: "Use jest.mock for module mocking",
        description:
          "jest.mock() automatically mocks an entire module. Use jest.fn() for " +
          "individual functions and jest.spyOn() to spy on existing implementations.",
        source: "Built-in knowledge",
        priority: "high",
      },
    ],
  },
  deployment: {
    Docker: [
      {
        title: "Use multi-stage builds",
        description:
          "Multi-stage builds reduce the final image size by separating " +
          "the build environment from the production environment. Use lightweight base images like alpine.",
        source: "Built-in knowledge",
        priority: "high",
      },
      {
        title: "Healthcheck in Dockerfile",
        description:
          "Add HEALTHCHECK instruction in the Dockerfile so orchestrators " +
          "like Kubernetes or Docker Swarm can monitor container status.",
        source: "Built-in knowledge",
        priority: "medium",
      },
    ],
    "Node.js": [
      {
        title: "Use a process manager for production",
        description:
          "PM2 or Docker with restart policy ensures the application stays running " +
          "after a crash. Do not use node directly in production.",
        source: "Built-in knowledge",
        priority: "high",
      },
    ],
  },
  api: {
    Express: [
      {
        title: "Use express-validator for input validation",
        description:
          "express-validator provides middleware for validating request body, params, and query. " +
          "This prevents injection attacks and invalid data.",
        source: "Built-in knowledge",
        priority: "high",
      },
      {
        title: "Rate limiting with express-rate-limit",
        description:
          "Use express-rate-limit to prevent brute force and DDoS attacks. " +
          "Configure the limit per IP according to endpoint needs.",
        source: "Built-in knowledge",
        priority: "high",
      },
    ],
    "Next.js": [
      {
        title: "Route handlers for API endpoints",
        description:
          "Use route.ts or route.js files in the app directory of Next.js 13+ to " +
          "create API endpoints with full support for HTTP methods.",
        source: "Built-in knowledge",
        priority: "high",
      },
    ],
  },
  error_handling: {
    "Node.js": [
      {
        title: "Global error handler middleware",
        description:
          "Create a global error handler middleware that catches all uncaught errors. " +
          "In Express, this is middleware with 4 parameters (err, req, res, next).",
        source: "Built-in knowledge",
        priority: "high",
      },
      {
        title: "Structured error response",
        description:
          "Use a consistent error response format: { success: false, error: { code, message, details } }. " +
          "This makes it easier for clients to handle errors programmatically.",
        source: "Built-in knowledge",
        priority: "medium",
      },
    ],
  },
};

/**
 * Task types supported by the best practices engine.
 */
const SUPPORTED_TASK_TYPES = [
  "authentication",
  "database",
  "testing",
  "deployment",
  "api",
  "error_handling",
  "routing",
  "state_management",
  "styling",
  "caching",
  "logging",
  "monitoring",
  "ci_cd",
  "security",
  "performance",
] as const;

export type SupportedTaskType = (typeof SUPPORTED_TASK_TYPES)[number];

/**
 * Get best practice suggestions based on task type and project framework.
 *
 * This function will:
 * 1. Look up best practices from the built-in database
 * 2. Also search stored knowledge entries for additional suggestions
 * 3. Merge and sort by priority
 *
 * @param taskType - The type of task being worked on
 * @param projectFramework - The framework used by the project
 * @returns Array of best practice suggestions (sorted by priority: high, medium, low)
 *
 * @example
 * ```ts
 * const suggestions = suggestBestPractices("authentication", "Next.js");
 * for (const s of suggestions) {
 *   console.log(`[${s.priority}] ${s.title}: ${s.description}`);
 * }
 * ```
 */
export function suggestBestPractices(
  taskType: string,
  projectFramework: string,
): BestPracticeSuggestion[] {
  const suggestions: BestPracticeSuggestion[] = [];

  try {
    // 1. Built-in suggestions
    const taskSuggestions = BUILT_IN_BEST_PRACTICES[taskType.toLowerCase()];
    if (taskSuggestions) {
      // Search for specific framework
      const frameworkSuggestions = taskSuggestions[projectFramework];
      if (frameworkSuggestions) {
        suggestions.push(...frameworkSuggestions);
      }

      // Search for generic framework (if any)
      const genericSuggestions = taskSuggestions["*"];
      if (genericSuggestions) {
        suggestions.push(...genericSuggestions);
      }
    }

    // 2. Add from stored knowledge entries
    const queryResult = queryProjectKnowledge(`${taskType} ${projectFramework}`);
    for (const entry of queryResult.entries) {
      // Only add if relevant (content contains best practice keywords)
      const contentLower = entry.content.toLowerCase();
      if (
        contentLower.includes("best practice") ||
        contentLower.includes("recommend") ||
        contentLower.includes("should")
      ) {
        suggestions.push({
          title: `${entry.library}: ${entry.topic}`,
          description: entry.content.slice(0, 300),
          source: `${entry.source} — ${entry.library}`,
          priority: "medium",
        });
      }
    }

    // 3. Sort by priority: high -> medium -> low
    const priorityOrder = { high: 0, medium: 1, low: 2 };
    suggestions.sort(
      (a, b) => (priorityOrder[a.priority] ?? 99) - (priorityOrder[b.priority] ?? 99),
    );

    return suggestions;
  } catch (error) {
    console.error(`[knowledge-integrator] Error generating suggestions: ${error}`);
    return suggestions;
  }
}

/**
 * Task tips database for "Did you know?" contextual tips.
 */
const BUILT_IN_TIPS: Array<{
  category: string;
  keywords: string[];
  message: string;
  reasoning: string;
}> = [
  {
    category: "TypeScript",
    keywords: ["typescript", "ts", "type", "interface", "generic"],
    message:
      "TypeScript 5.0+ supports decorators that are compliant with the ECMAScript standard. " +
      "Use `experimentalDecorators: false` to use the new standard decorators.",
    reasoning: "Standard decorators are more future-proof and natively supported by ECMAScript.",
  },
  {
    category: "Next.js",
    keywords: ["nextjs", "next.js", "next", "ssr", "server component"],
    message:
      "Next.js 13+ App Router uses Server Components by default. " +
      "Only add 'use client' if the component truly needs client-side interactivity.",
    reasoning: "Server Components reduce JavaScript bundle size and improve performance.",
  },
  {
    category: "React",
    keywords: ["react", "component", "hook", "state", "useEffect"],
    message:
      "Use React Query (TanStack Query) for data fetching instead of useEffect + useState. " +
      "React Query handles caching, refetching, and optimistic updates automatically.",
    reasoning:
      "React Query eliminates data fetching boilerplate and provides caching out-of-the-box.",
  },
  {
    category: "Prisma",
    keywords: ["prisma", "orm", "database", "schema", "migration"],
    message:
      "Prisma supports composite indexes in the schema. Use @@index([field1, field2]) " +
      "for queries that frequently use multiple fields in the WHERE clause.",
    reasoning: "Composite indexes speed up queries that filter on multiple columns at once.",
  },
  {
    category: "Express",
    keywords: ["express", "middleware", "route", "api"],
    message:
      "Use the `express-async-errors` package so that async route handlers " +
      "that throw errors automatically forward them to the error handling middleware without manual try/catch.",
    reasoning:
      "Reduces try/catch boilerplate in every route handler and prevents unhandled promise rejections.",
  },
  {
    category: "Docker",
    keywords: ["docker", "container", "image", "dockerfile"],
    message:
      "Use .dockerignore to exclude node_modules and unnecessary files. " +
      "This reduces build context size and significantly speeds up build time.",
    reasoning: "A large Docker build context slows down the build process and image transfer.",
  },
  {
    category: "Testing",
    keywords: ["test", "testing", "jest", "vitest", "unit test"],
    message:
      "Use the `--changed` flag in Vitest to run tests only for changed files. " +
      "This saves time during development: `npx vitest --changed`.",
    reasoning: "Running all tests on every change is inefficient for the development loop.",
  },
  {
    category: "Node.js",
    keywords: ["node", "nodejs", "node.js", "backend", "server"],
    message:
      "Node.js 20+ has a built-in fetch API (based on undici). " +
      "You no longer need to install `node-fetch` or `axios` for simple HTTP requests.",
    reasoning: "Reduces external dependencies and shrinks node_modules.",
  },
  {
    category: "Performance",
    keywords: ["perf", "performance", "optimization", "bundle", "lazy"],
    message:
      "Use `lazy` loading for components that are not immediately visible on initial page load. " +
      "In Next.js, use `next/dynamic`; in plain React, use `React.lazy()`.",
    reasoning:
      "Lazy loading reduces the initial bundle size and speeds up First Contentful Paint (FCP).",
  },
  {
    category: "CSS",
    keywords: ["css", "styling", "tailwind", "responsive"],
    message:
      "Tailwind CSS v4 uses CSS-first configuration. You can use " +
      "@import 'tailwindcss' in your main CSS file without needing tailwind.config.js.",
    reasoning: "CSS-first config reduces boilerplate and feels more natural for CSS developers.",
  },
  {
    category: "Git",
    keywords: ["git", "commit", "branch", "version control"],
    message:
      "Use conventional commits to auto-generate changelogs. " +
      "Format: `type(scope): description` — example: `feat(auth): add login endpoint`.",
    reasoning:
      "Conventional commits enable semantic versioning and automatic changelog generation.",
  },
  {
    category: "Security",
    keywords: ["security", "auth", "jwt", "token", "password", "encrypt"],
    message:
      "Never store secret keys in source code. Use environment variables " +
      "or a secret management service like AWS Secrets Manager or HashiCorp Vault.",
    reasoning: "Hardcoded secrets are one of the most common causes of data leaks on GitHub.",
  },
  {
    category: "Database",
    keywords: ["database", "query", "sql", "index", "n+1"],
    message:
      "Watch out for the N+1 query problem: when you fetch a list of items and then query each item " +
      "individually. Use JOIN or batch queries to address this.",
    reasoning:
      "N+1 queries increase latency linearly with the amount of data and can cause timeouts.",
  },
  {
    category: "State Management",
    keywords: ["state", "redux", "context", "global state", "zustand"],
    message:
      "For simple state management, use Zustand instead of Redux. " +
      "Zustand has a minimal API, no boilerplate, and a bundle size of only ~1KB.",
    reasoning:
      "Redux has excessive boilerplate for applications with simple state management needs.",
  },
  {
    category: "API Design",
    keywords: ["api", "rest", "graphql", "endpoint", "route"],
    message:
      "Use semantic API versioning in the URL (like /api/v1/) or HTTP headers " +
      "to avoid breaking changes for old clients when you update the API.",
    reasoning:
      "API versioning allows you to release major changes without affecting existing clients.",
  },
];

/**
 * Generate a contextual tip ("Did you know?") based on task context.
 *
 * This function will:
 * 1. Match the task context against built-in tip keywords
 * 2. Also search in knowledge entries for additional tips
 * 3. Return the most relevant tip for the context
 *
 * @param taskContext - Description of the task context being worked on
 * @returns Formatted tip string, or a default message if no relevant tip is found
 *
 * @example
 * ```ts
 * const tip = generateContextTip("Building authentication with Next.js and Prisma");
 * // Output: "💡 Did you know? Next.js 13+ App Router uses Server Components..."
 * ```
 */
export function generateContextTip(taskContext: string): string {
  if (!taskContext || !taskContext.trim()) {
    return "💡 Tip: Add task context to get relevant suggestions.";
  }

  try {
    const contextLower = taskContext.toLowerCase();
    const matchedTips: Array<{ tip: (typeof BUILT_IN_TIPS)[0]; score: number }> = [];

    // 1. Search from built-in tips
    for (const tip of BUILT_IN_TIPS) {
      let score = 0;

      for (const keyword of tip.keywords) {
        if (contextLower.includes(keyword)) {
          score += 2;
        }

        // Search word by word
        const keywordParts = keyword.split(/\s+/);
        for (const part of keywordParts) {
          if (part.length > 2 && contextLower.includes(part)) {
            score += 1;
          }
        }
      }

      if (score > 0) {
        matchedTips.push({ tip, score });
      }
    }

    // 2. Search from stored knowledge entries
    const knowledgeResult = queryProjectKnowledge(taskContext);
    const knowledgeTips: string[] = [];

    for (const entry of knowledgeResult.entries.slice(0, 3)) {
      // Take the first sentence from content as the tip
      const firstSentence = entry.content.split(/[.!?\n]/).filter(Boolean)[0];
      if (firstSentence && firstSentence.length < 200) {
        knowledgeTips.push(`[${entry.library}] ${firstSentence.trim()}`);
      }
    }

    // 3. Select tip with the highest score
    matchedTips.sort((a, b) => b.score - a.score);

    if (matchedTips.length > 0) {
      const bestTip = matchedTips[0].tip;
      return `💡 Did you know? ${bestTip.message}\n   Why: ${bestTip.reasoning}`;
    }

    if (knowledgeTips.length > 0) {
      return `💡 Did you know? ${knowledgeTips[0]}`;
    }

    return "💡 Tip: Try documenting new knowledge with addManualKnowledge() or fetchLibraryDocs().";
  } catch (error) {
    // Silent fallback — errors should not disrupt UX
    return "💡 Tip: Documentation is a long-term investment. The more knowledge stored, the smarter the suggestions become.";
  }
}

// ─── Stats ──────────────────────────────────────────────────────────────

/**
 * Get complete statistics from the knowledge base.
 *
 * Calculates:
 * - Total entries
 * - Count per library
 * - Count per source (context7, web, manual)
 * - Top 10 most frequent topics
 *
 * @returns KnowledgeStats with all metrics
 *
 * @example
 * ```ts
 * const stats = getKnowledgeStats();
 * console.log(`Total entries: ${stats.totalEntries}`);
 * console.log(`By library:`, stats.byLibrary);
 * console.log(`Top topics:`, stats.topTopics);
 * ```
 */
export function getKnowledgeStats(): KnowledgeStats {
  try {
    const entries = loadEntries();

    const byLibrary: Record<string, number> = {};
    const bySource: Record<"context7" | "web" | "manual", number> = {
      context7: 0,
      web: 0,
      manual: 0,
    };
    const topicCount: Record<string, number> = {};

    for (const entry of entries) {
      // By library
      const lib = entry.library || "unknown";
      byLibrary[lib] = (byLibrary[lib] ?? 0) + 1;

      // By source
      if (entry.source in bySource) {
        bySource[entry.source] += 1;
      }

      // By topic
      const topic = entry.topic || "untagged";
      topicCount[topic] = (topicCount[topic] ?? 0) + 1;
    }

    // Top 10 topics
    const topTopics = Object.entries(topicCount)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10)
      .map(([topic, count]) => ({ topic, count }));

    return {
      totalEntries: entries.length,
      byLibrary,
      bySource,
      topTopics,
    };
  } catch (error) {
    console.error(`[knowledge-integrator] Error getting stats: ${error}`);
    return {
      totalEntries: 0,
      byLibrary: {},
      bySource: { context7: 0, web: 0, manual: 0 },
      topTopics: [],
    };
  }
}

// ─── Formatting ─────────────────────────────────────────────────────────

/**
 * Format a KnowledgeEntry array into human-readable Markdown report.
 *
 * Output format:
 * - Summary of entry count
 * - Each entry displayed with ID, timestamp, source, library, topic
 * - Content truncated if too long
 * - Tags displayed as badges
 *
 * @param entries - Array of KnowledgeEntry to format
 * @returns Formatted Markdown string
 *
 * @example
 * ```ts
 * const report = formatKnowledgeReport(queryResult.entries);
 * console.log(report);
 * // Output:
 * // # Knowledge Report (5 entries)
 * // ...
 * ```
 */
export function formatKnowledgeReport(entries: KnowledgeEntry[]): string {
  if (!entries || entries.length === 0) {
    return "# Knowledge Report\n\n_No entries found._";
  }

  const lines: string[] = [];
  lines.push(`# Knowledge Report`);
  lines.push("");
  lines.push(`**Total entries:** ${entries.length}`);
  lines.push("");

  for (let index = 0; index < entries.length; index++) {
    const entry = entries[index];

    lines.push(`## ${index + 1}. ${entry.library}: ${entry.topic}`);
    lines.push("");
    lines.push(`| Field | Value |`);
    lines.push(`|-------|-------|`);
    lines.push(`| **ID** | \`${entry.id}\` |`);
    lines.push(`| **Timestamp** | ${entry.timestamp} |`);
    lines.push(`| **Library** | ${entry.library} |`);
    lines.push(`| **Source** | ${entry.source} |`);

    if (entry.url) {
      lines.push(`| **URL** | ${entry.url} |`);
    }

    // Tags
    if (entry.tags.length > 0) {
      const tags = entry.tags.map((t) => `\`${t}\``).join(", ");
      lines.push(`| **Tags** | ${tags} |`);
    }

    // Relevance
    if (entry.relevance.length > 0) {
      lines.push(`| **Keywords** | ${entry.relevance.join(", ")} |`);
    }

    lines.push("");

    // Content (truncated for readability)
    const maxContentLength = 500;
    const content =
      entry.content.length > maxContentLength
        ? entry.content.slice(0, maxContentLength) +
          `... _(truncated, ${entry.content.length} chars total)_`
        : entry.content;

    lines.push("### Content");
    lines.push("");
    lines.push(content);
    lines.push("");

    if (index < entries.length - 1) {
      lines.push("---");
      lines.push("");
    }
  }

  return lines.join("\n");
}

/**
 * Format knowledge base statistics into human-readable Markdown.
 *
 * @param stats - KnowledgeStats to format
 * @returns Formatted Markdown string
 *
 * @example
 * ```ts
 * const stats = getKnowledgeStats();
 * console.log(formatKnowledgeStats(stats));
 * ```
 */
export function formatKnowledgeStats(stats: KnowledgeStats): string {
  const lines: string[] = [];

  lines.push("# Knowledge Base Statistics");
  lines.push("");
  lines.push(`**Total entries:** ${stats.totalEntries}`);
  lines.push("");

  // By source
  lines.push("## By Source");
  lines.push("| Source | Count |");
  lines.push("|--------|-------|");
  lines.push(`| Context7 | ${stats.bySource.context7} |`);
  lines.push(`| Web | ${stats.bySource.web} |`);
  lines.push(`| Manual | ${stats.bySource.manual} |`);
  lines.push("");

  // By library (top 15)
  const sortedLibraries = Object.entries(stats.byLibrary)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 15);

  if (sortedLibraries.length > 0) {
    lines.push("## By Library (top 15)");
    lines.push("| Library | Count |");
    lines.push("|---------|-------|");
    for (const [lib, count] of sortedLibraries) {
      lines.push(`| ${lib} | ${count} |`);
    }
    lines.push("");
  }

  // Top topics
  if (stats.topTopics.length > 0) {
    lines.push("## Top Topics");
    lines.push("| Topic | Count |");
    lines.push("|-------|-------|");
    for (const topic of stats.topTopics) {
      lines.push(`| ${topic.topic} | ${topic.count} |`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Format knowledge query results into human-readable Markdown.
 *
 * @param result - KnowledgeQueryResult to format
 * @returns Formatted Markdown string
 *
 * @example
 * ```ts
 * const result = queryProjectKnowledge("Next.js authentication");
 * console.log(formatQueryResult(result));
 * ```
 */
export function formatQueryResult(result: KnowledgeQueryResult): string {
  const lines: string[] = [];

  lines.push(`# Knowledge Query: "${result.question}"`);
  lines.push("");
  lines.push(`**Total matches:** ${result.totalMatches}`);
  lines.push(`**Displayed:** ${result.entries.length}`);
  lines.push("");

  if (result.entries.length === 0) {
    lines.push("_No relevant entries found._");
    lines.push("");
    lines.push("💡 **Tips:**");
    lines.push("- Use more general keywords");
    lines.push("- Try adding knowledge first with `addManualKnowledge()`");
    lines.push("- Or use `fetchLibraryDocs()` to fetch documentation from Context7");
    return lines.join("\n");
  }

  for (let index = 0; index < result.entries.length; index++) {
    const entry = result.entries[index];

    lines.push(`### ${index + 1}. [${entry.source}] ${entry.library} — ${entry.topic}`);
    lines.push("");
    lines.push(`- **ID:** \`${entry.id}\``);
    lines.push(`- **Source:** ${entry.source}`);
    lines.push(`- **Timestamp:** ${entry.timestamp}`);

    if (entry.url) {
      lines.push(`- **URL:** ${entry.url}`);
    }

    if (entry.tags.length > 0) {
      lines.push(`- **Tags:** ${entry.tags.join(", ")}`);
    }

    lines.push("");
    // Content excerpt
    const excerpt =
      entry.content.length > 250 ? entry.content.slice(0, 250) + "..." : entry.content;
    lines.push(excerpt);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Format best practice suggestions into human-readable Markdown.
 *
 * @param suggestions - Array of BestPracticeSuggestion
 * @param taskType - Task type (for report title)
 * @param framework - Framework being used
 * @returns Formatted Markdown string
 */
export function formatSuggestions(
  suggestions: BestPracticeSuggestion[],
  taskType: string,
  framework: string,
): string {
  const lines: string[] = [];

  lines.push(`# Best Practices: ${taskType} for ${framework}`);
  lines.push("");
  lines.push(`**Total suggestions:** ${suggestions.length}`);
  lines.push("");

  if (suggestions.length === 0) {
    lines.push("_No best practice suggestions available._");
    lines.push("");
    lines.push("💡 Use `fetchLibraryDocs()` to fetch the latest documentation.");
    return lines.join("\n");
  }

  const priorityLabels: Record<string, string> = {
    high: "🔴 High Priority",
    medium: "🟡 Medium Priority",
    low: "🟢 Nice to Have",
  };

  // Group by priority
  const byPriority: Record<string, BestPracticeSuggestion[]> = { high: [], medium: [], low: [] };
  for (const s of suggestions) {
    const p = s.priority in byPriority ? s.priority : "medium";
    byPriority[p].push(s);
  }

  for (const priority of ["high", "medium", "low"] as const) {
    const group = byPriority[priority] ?? [];
    if (group.length === 0) continue;

    lines.push(`## ${priorityLabels[priority] ?? priority}`);
    lines.push("");

    for (let index = 0; index < group.length; index++) {
      const s = group[index];
      lines.push(`### ${index + 1}. ${s.title}`);
      lines.push("");
      lines.push(s.description);
      lines.push("");
      lines.push(`_Source: ${s.source}_`);
      lines.push("");
    }
  }

  return lines.join("\n");
}
