#!/usr/bin/env node
/**
 * PR Description & Changelog Generator
 *
 * Auto-generate PR descriptions from git diff + conventional commits.
 * Generate changelog from git tags.
 */

import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export interface PRDescriptionOptions {
  targetBranch?: string;
  includeSummary?: boolean;
  includeChecklist?: boolean;
}

export interface PrDescription {
  title: string;
  body: string;
  commits: number;
  filesChanged: number;
}

export interface ChangelogEntry {
  version: string;
  date: string;
  features: string[];
  fixes: string[];
  chores: string[];
  breaking: string[];
  refactors: string[];
}

// ─── PR Description ────────────────────────────────────────────────────

export function generatePRDescription(options?: PRDescriptionOptions): PrDescription {
  const target = options?.targetBranch ?? "main";

  // Get branch name
  const branch = execSync("git rev-parse --abbrev-ref HEAD", { encoding: "utf-8" }).trim();

  // Get commit log since target
  const log = execSync(`git log ${target}..HEAD --oneline --no-decorate 2>/dev/null || git log --oneline -20`, { encoding: "utf-8" }).trim();
  const commits = log.split("\n").filter(Boolean);

  // Get diff stat
  const diffStat = execSync(`git diff ${target}..HEAD --stat 2>/dev/null || git diff --stat HEAD~5`, { encoding: "utf-8" }).trim();
  const filesChanged = diffStat.split("\n").filter((l) => l.includes("|")).length;

  // Categorize commits
  const features: string[] = [];
  const fixes: string[] = [];
  const chores: string[] = [];
  const breaking: string[] = [];

  for (const commit of commits) {
    const msg = commit.replace(/^[a-f0-9]+\s+/, "");
    if (/^feat/i.test(msg)) features.push(msg);
    else if (/^fix/i.test(msg)) fixes.push(msg);
    else if (/^breaking/i.test(msg) || /!:/i.test(msg)) breaking.push(msg);
    else if (/^chore/i.test(msg) || /^docs/i.test(msg) || /^test/i.test(msg)) chores.push(msg);
    else features.push(msg); // default to feature
  }

  // Generate title
  const firstCommit = commits[0]?.replace(/^[a-f0-9]+\s+/, "") ?? "";
  const title = firstCommit.length > 80 ? firstCommit.slice(0, 77) + "..." : firstCommit || `Changes from ${branch}`;

  // Build body
  const bodyParts: string[] = [];

  if (options?.includeSummary !== false) {
    bodyParts.push("## Summary", "", commits.length > 0
      ? `This PR contains **${commits.length} commits** across **${filesChanged} files**.`
      : "Changes in this branch.", "");
  }

  if (features.length > 0) {
    bodyParts.push("### ✨ Features", ...features.map((f) => `- ${f}`), "");
  }
  if (fixes.length > 0) {
    bodyParts.push("### 🐛 Bug Fixes", ...fixes.map((f) => `- ${f}`), "");
  }
  if (breaking.length > 0) {
    bodyParts.push("### ⚠️ Breaking Changes", ...breaking.map((b) => `- ${b}`), "");
  }
  if (chores.length > 0) {
    bodyParts.push("### 🔧 Maintenance", ...chores.map((c) => `- ${c}`), "");
  }

  if (options?.includeChecklist !== false) {
    bodyParts.push(
      "## Checklist",
      "",
      "- [ ] Tests pass",
      "- [ ] No dummy/debug code",
      "- [ ] Documentation updated (if needed)",
      "- [ ] Reviewed for security concerns",
      "",
    );
  }

  bodyParts.push("---", "", "_Generated by coder-workflow_");

  return {
    title,
    body: bodyParts.join("\n"),
    commits: commits.length,
    filesChanged,
  };
}

// ─── Changelog ──────────────────────────────────────────────────────────

export function generateChangelog(from?: string, to?: string): ChangelogEntry[] {
  // Get tags
  const tags = execSync("git tag --sort=-version:refname 2>/dev/null || echo 'no tags'", { encoding: "utf-8" })
    .trim()
    .split("\n")
    .filter(Boolean);

  if (tags.length === 0 || tags[0] === "no tags") {
    // No tags — generate from recent commits
    return [generateSingleChangelog("Unreleased", undefined)];
  }

  const entries: ChangelogEntry[] = [];

  // Add "Unreleased" if HEAD not at a tag
  const headTag = execSync("git tag --points-at HEAD 2>/dev/null", { encoding: "utf-8" }).trim();
  if (!headTag) {
    entries.push(generateSingleChangelog("Unreleased", undefined));
  }

  // Generate between tags
  for (let i = 0; i < tags.length; i++) {
    const current = tags[i];
    const previous = tags[i + 1];

    if (from && from !== current) continue;
    entries.push(generateSingleChangelog(current, previous));
    if (from && from === current) break;
  }

  if (to && entries.length > 0) {
    const toIndex = entries.findIndex((e) => e.version === to);
    if (toIndex >= 0) return entries.slice(0, toIndex + 1);
  }

  return entries.slice(0, 10);
}

function generateSingleChangelog(version: string, previous?: string): ChangelogEntry {
  let log = "";
  try {
    if (previous) {
      log = execSync(`git log ${previous}..HEAD --oneline --no-decorate 2>/dev/null`, { encoding: "utf-8" });
    } else {
      log = execSync("git log --oneline -30 --no-decorate 2>/dev/null", { encoding: "utf-8" });
    }
  } catch {
    log = "";
  }

  const commits = log.trim().split("\n").filter(Boolean);
  const features: string[] = [];
  const fixes: string[] = [];
  const chores: string[] = [];
  const breaking: string[] = [];
  const refactors: string[] = [];

  for (const commit of commits) {
    const msg = commit.replace(/^[a-f0-9]+\s+/, "");
    if (/^feat/i.test(msg)) features.push(msg.replace(/^feat(\([^)]+\))?:\s*/i, ""));
    else if (/^fix/i.test(msg)) fixes.push(msg.replace(/^fix(\([^)]+\))?:\s*/i, ""));
    else if (/^breaking/i.test(msg) || /!:/i.test(msg)) breaking.push(msg.replace(/^[^(]*\)?!?:\s*/i, ""));
    else if (/^refactor/i.test(msg)) refactors.push(msg.replace(/^refactor(\([^)]+\))?:\s*/i, ""));
    else if (/^chore|^docs|^test|^build/i.test(msg)) chores.push(msg.replace(/^(chore|docs|test|build)(\([^)]+\))?:\s*/i, ""));
  }

  return {
    version,
    date: new Date().toISOString().split("T")[0],
    features,
    fixes,
    chores,
    breaking,
    refactors,
  };
}

// ─── Release Manager ───────────────────────────────────────────────────

export interface ReleaseResult {
  newVersion: string;
  tag: string;
  changelog: ChangelogEntry[];
}

export function createRelease(bump: "patch" | "minor" | "major"): ReleaseResult {
  const pkgPath = join(process.cwd(), "package.json");
  if (!existsSync(pkgPath)) {
    throw new Error("No package.json found");
  }

  const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
  const current = pkg.version || "0.0.0";
  const parts = current.split(".").map(Number);

  switch (bump) {
    case "major": parts[0]++; parts[1] = 0; parts[2] = 0; break;
    case "minor": parts[1]++; parts[2] = 0; break;
    case "patch": parts[2]++; break;
  }

  const newVersion = parts.join(".");
  const tag = `v${newVersion}`;

  // Generate changelog
  const changelog = generateSingleChangelog(newVersion, current !== "0.0.0" ? `v${current}` : undefined);

  return { newVersion, tag, changelog: [changelog] };
}

// ─── CLI Helpers ───────────────────────────────────────────────────────

export function formatChangelogMarkdown(entries: ChangelogEntry[]): string {
  const parts: string[] = ["# Changelog", ""];

  for (const entry of entries) {
    parts.push(`## ${entry.version} — ${entry.date}`, "");

    if (entry.breaking.length > 0) {
      parts.push("### ⚠️ Breaking Changes", ...entry.breaking.map((b) => `- ${b}`), "");
    }
    if (entry.features.length > 0) {
      parts.push("### 🚀 Features", ...entry.features.map((f) => `- ${f}`), "");
    }
    if (entry.fixes.length > 0) {
      parts.push("### 🐛 Bug Fixes", ...entry.fixes.map((f) => `- ${f}`), "");
    }
    if (entry.refactors.length > 0) {
      parts.push("### ♻️ Refactors", ...entry.refactors.map((r) => `- ${r}`), "");
    }
    if (entry.chores.length > 0) {
      parts.push("### 📦 Maintenance", ...entry.chores.map((c) => `- ${c}`), "");
    }
  }

  return parts.join("\n");
}
