#!/usr/bin/env node
/**
 * Skill Curator (Procedural Memory)
 *
 * Simulates Hermes-Agent's Curator system to auto-generate, track,
 * and archive procedural memory skills based on their usage.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  renameSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

const SKILLS_DIR = "skills";
const ARCHIVE_DIR = "skills/.archive";
const USAGE_FILE = ".claude/skill-curator/usage.json";

interface SkillUsage {
  skillName: string;
  useCount: number;
  lastUsed: string;
}

function ensureCuratorDir(): string {
  const dir = join(process.cwd(), ".claude", "skill-curator");
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  return dir;
}

function loadUsage(): Record<string, SkillUsage> {
  const dir = ensureCuratorDir();
  const file = join(dir, "usage.json");
  if (!existsSync(file)) return {};
  try {
    return JSON.parse(readFileSync(file, "utf-8"));
  } catch {
    return {};
  }
}

function saveUsage(usage: Record<string, SkillUsage>): void {
  const dir = ensureCuratorDir();
  writeFileSync(join(dir, "usage.json"), JSON.stringify(usage, null, 2), "utf-8");
}

/**
 * Scaffolds a new executable skill after a successful complex task.
 */
export function scaffoldNewSkill(skillName: string, description: string, workflow: string): string {
  const skillsDir = join(process.cwd(), SKILLS_DIR);
  if (!existsSync(skillsDir)) mkdirSync(skillsDir, { recursive: true });

  const targetDir = join(skillsDir, skillName);
  if (!existsSync(targetDir)) mkdirSync(targetDir, { recursive: true });

  const mdContent = `---
name: ${skillName}
description: ${description}
version: 1.0.0
platforms: [linux, macos]
metadata.hermes.category: Auto-Learned
---

# ${skillName}

${description}

## When to Use
Use this skill when you need to automate the task related to ${skillName}.

## Procedure
${workflow}

*Auto-generated by coder-workflow Skill Curator.*
`;

  writeFileSync(join(targetDir, "SKILL.md"), mdContent, "utf-8");
  return join(targetDir, "SKILL.md");
}

/**
 * Records that a skill was used.
 */
export function recordSkillUsage(skillName: string): void {
  const usage = loadUsage();
  if (!usage[skillName]) {
    usage[skillName] = { skillName, useCount: 0, lastUsed: new Date().toISOString() };
  }
  usage[skillName].useCount += 1;
  usage[skillName].lastUsed = new Date().toISOString();
  saveUsage(usage);
}

/**
 * Scans the skills directory and archives stale skills.
 */
export function pruneStaleSkills(maxIdleDays = 30): { archived: string[] } {
  const skillsDir = join(process.cwd(), SKILLS_DIR);
  const archiveDir = join(process.cwd(), ARCHIVE_DIR);

  if (!existsSync(skillsDir)) return { archived: [] };
  if (!existsSync(archiveDir)) mkdirSync(archiveDir, { recursive: true });

  const usage = loadUsage();
  const archived: string[] = [];
  const now = new Date().getTime();

  const entries = readdirSync(skillsDir);
  for (const entry of entries) {
    if (entry === ".archive") continue;

    const skillPath = join(skillsDir, entry);
    if (!statSync(skillPath).isDirectory()) continue;

    const skillUsage = usage[entry];
    let lastUsedTime = statSync(skillPath).mtime.getTime();

    if (skillUsage) {
      lastUsedTime = new Date(skillUsage.lastUsed).getTime();
    }

    const idleDays = (now - lastUsedTime) / (1000 * 60 * 60 * 24);
    if (idleDays > maxIdleDays) {
      // Archive it
      const archiveDest = join(archiveDir, entry);
      renameSync(skillPath, archiveDest);
      archived.push(entry);
    }
  }

  return { archived };
}
